name: Action Accessible from Repositories within the enterprise

on:
  issues:
    types:
      - opened
      - edited

# expected issue body input should be structured as follows:
#     {
#         "rep01": {
#             "repository": "rep01",
#             "organisation": "org01"
#         },
#         "rep02": {
#             "repository": "rep02",
#             "organisation": "org02"
#         } 
#     }

permissions:
  contents: read
  issues: write    

jobs:
  resubale-workflow-access:
    if: contains(github.event.issue.labels.*.name, 'post-mg-steps')
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pandas
          pip install openpyxl

      - name: Run Python script
        id: python-script
        run: |
          python script/python-script.py "${{ matrix.repository }}"  # Pass the repository name as an argument

      - name: Allowing access to components in an internal repository
        run: |
          if [ "${{ steps.python-script.outputs.allowAccess }}" == "true" ]; then
            curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}/${{ matrix.repository }}/actions/permissions/access \
            -d '{
              "access_level":"enterprise"
            }'
          else
            curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}/${{ matrix.repository }}/actions/permissions/access \
            -d '{
              "access_level":"organization"
            }'
          fi  
